version: '3.7'

services:

  server:
    container_name: deuschat
    build:
      context: .
    volumes:
      - .:/usr/src/app/my-app
      - /usr/src/app/my-app/node_modules
    ports:
      - 3000:3000
    stdin_open: true
